python mainC.py polbooks.graph.txt -cB -NonDef
python mainC.py adjnoun.graph.txt -cB -NonDef
python mainC.py celegans_metabolic.graph.txt -cB -NonDef
python mainC.py delaunay_n10.graph.txt -cB -NonDef
python mainC.py email.graph.txt -cB -NonDef 
python mainC.py polblogs.graph.txt -cB -NonDef 
python mainC.py netscience.graph.txt -cB -NonDef
python mainC.py delaunay_n11.graph.txt -cB -NonDef
python mainC.py power.graph.txt -cB -NonDef
python mainC.py PGPgiantcompo.graph.txt -cB -NonDef
python mainC.py astro-ph.graph.txt -cB -NonDef
python mainC.py cond-mat.graph.txt -cB -NonDef
python mainC.py memplus.graph.txt -cB -NonDef
python mainC.py as-22july06.graph.txt -cB -NonDef
python mainC.py cond-mat-2003.graph.txt -cB -NonDef
python mainC.py cond-mat-2005.graph.txt -cB -NonDef
python mainC.py G_n_pin_pout.graph.txt -cB -NonDef
python mainC.py smallworld.graph.txt -cB -NonDef
python mainC.py preferentialAttachment.graph.txt -cB -NonDef
python mainC.py luxembourg.osm.graph.txt -cB -NonDef
python mainC.py cnr-2000.graph.txt -cB -NonDef
python mainC.py preferentialAttachment.graph.txt -cB -NonDef
python mainC.py belgium.osm.graph.txt -cB -NonDef
python mainC.py Cit-HepPh.graph.txt -cB -NonDef
python mainC.py Cit-HepTh.graph.txt -cB -NonDef
python mainC.py Slashdot0811.graph.txt -cB -NonDef 
python mainC.py soc-Epinions.txt -cB -NonDef
python mainC.py web-NotreDame.graph.txt -cB -NonDef
python mainC.py Wiki-Vote.graph.txt -cB -NonDef
python mainC.py polbooks.graph.txt -sJ -NonDef
python mainC.py adjnoun.graph.txt -sJ -NonDef
python mainC.py celegans_metabolic.graph.txt -sJ -NonDef
python mainC.py delaunay_n10.graph.txt -sJ -NonDef
python mainC.py email.graph.txt -sJ -NonDef 
python mainC.py polblogs.graph.txt -sJ -NonDef 
python mainC.py netscience.graph.txt -sJ -NonDef
python mainC.py delaunay_n11.graph.txt -sJ -NonDef
python mainC.py power.graph.txt -sJ -NonDef
python mainC.py PGPgiantcompo.graph.txt -sJ -NonDef
python mainC.py astro-ph.graph.txt -sJ -NonDef
python mainC.py cond-mat.graph.txt -sJ -NonDef
python mainC.py memplus.graph.txt -sJ -NonDef
python mainC.py as-22july06.graph.txt -sJ -NonDef
python mainC.py cond-mat-2003.graph.txt -sJ -NonDef
python mainC.py cond-mat-2005.graph.txt -sJ -NonDef
python mainC.py G_n_pin_pout.graph.txt -sJ -NonDef
python mainC.py smallworld.graph.txt -sJ -NonDef
python mainC.py preferentialAttachment.graph.txt -sJ -NonDef
python mainC.py luxembourg.osm.graph.txt -sJ -NonDef
python mainC.py cnr-2000.graph.txt -sJ -NonDef
python mainC.py belgium.osm.graph.txt -sJ -NonDef
python mainC.py Cit-HepPh.graph.txt -sJ -NonDef
python mainC.py Cit-HepTh.graph.txt -sJ -NonDef
python mainC.py Slashdot0811.graph.txt -sJ -NonDef 
python mainC.py soc-Epinions.txt -sJ -NonDef
python mainC.py web-NotreDame.graph.txt -sJ -NonDef
python mainC.py Wiki-Vote.graph.txt -sJ -NonDef
python mainC.py preferentialAttachment.graph.txt -sJ -NonDef
python mainC.py polbooks.graph.txt -c -NonDef
python mainC.py adjnoun.graph.txt -c -NonDef
python mainC.py celegans_metabolic.graph.txt -c -NonDef
python mainC.py delaunay_n10.graph.txt -c -NonDef
python mainC.py email.graph.txt -c -NonDef 
python mainC.py polblogs.graph.txt -c -NonDef 
python mainC.py netscience.graph.txt -c -NonDef
python mainC.py delaunay_n11.graph.txt -c -NonDef
python mainC.py power.graph.txt -c -NonDef
python mainC.py PGPgiantcompo.graph.txt -c -NonDef
python mainC.py astro-ph.graph.txt -c -NonDef
python mainC.py cond-mat.graph.txt -c -NonDef
python mainC.py memplus.graph.txt -c -NonDef
python mainC.py as-22july06.graph.txt -c -NonDef
python mainC.py cond-mat-2003.graph.txt -c -NonDef
python mainC.py cond-mat-2005.graph.txt -c -NonDef
python mainC.py G_n_pin_pout.graph.txt -c -NonDef
python mainC.py smallworld.graph.txt -c -NonDef
python mainC.py preferentialAttachment.graph.txt -c -NonDef
python mainC.py luxembourg.osm.graph.txt -c -NonDef
python mainC.py cnr-2000.graph.txt -c -NonDef
python mainC.py preferentialAttachment.graph.txt -c -NonDef
python mainC.py polbooks.graph.txt -s -NonDef
python mainC.py adjnoun.graph.txt -s -NonDef
python mainC.py celegans_metabolic.graph.txt -s -NonDef
python mainC.py delaunay_n10.graph.txt -s -NonDef
python mainC.py email.graph.txt -s -NonDef 
python mainC.py polblogs.graph.txt -s -NonDef 
python mainC.py netscience.graph.txt -s -NonDef
python mainC.py delaunay_n11.graph.txt -s -NonDef
python mainC.py power.graph.txt -s -NonDef
python mainC.py PGPgiantcompo.graph.txt -s -NonDef
python mainC.py astro-ph.graph.txt -s -NonDef
python mainC.py cond-mat.graph.txt -s -NonDef
python mainC.py memplus.graph.txt -s -NonDef
python mainC.py as-22july06.graph.txt -s -NonDef
python mainC.py cond-mat-2003.graph.txt -s -NonDef
python mainC.py cond-mat-2005.graph.txt -s -NonDef
python mainC.py G_n_pin_pout.graph.txt -s -NonDef
python mainC.py smallworld.graph.txt -s -NonDef
python mainC.py preferentialAttachment.graph.txt -s -NonDef
python mainC.py luxembourg.osm.graph.txt -s -NonDef
python mainC.py cnr-2000.graph.txt -s -NonDef
python mainC.py preferentialAttachment.graph.txt -s -NonDef